#!/bin/sh  
#chkconfig:2345 70 30  
#description:ngrok  
 
ngrok_path=/usr/local/ngrok
case "$1" in
    start)
        echo "start ngrok service....."  
        sh /usr/local/ngrok/start.sh
        ;;
    *)
    exit 1
    ;;
esac
